export const ApiPrueba = [
    {
        "id": 1,
        "ot": "OT-0001",
        "placa": "ABC-123",
        "asesor": "Asesor 1",
        "tecnicoMecanico": "Tecnico 1",
        "elevador": "Elevador 1",
        "fecha": "2020-01-01",
        "estado": "Pendiente",
        "confirmacionPicking": "Terminado",
    },
    {
        "id": 2,
        "ot": "OT-0002",
        "placa": "ABC-456",
        "asesor": "Asesor 3",
        "tecnicoMecanico": "Tecnico 2",
        "elevador": "Elevador 2",
        "fecha": "2020-01-01",
        "estado": "En proceso",
        "confirmacionPicking": "Terminado",
    },
    {
        "id": 3,
        "ot": "OT-0003",
        "placa": "ABC-789",
        "asesor": "Asesor 2",
        "tecnicoMecanico": "Tecnico 3",
        "elevador": "Elevador 3",
        "fecha": "2020-01-01",
        "estado": "En pausa",
        "confirmacionPicking": "Terminado",
    }
]