export const DataRecepcion = [
  {
    id: 1,
    placa: "VGGJ4464",
    nombre: "Rodolfo Gilardi",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaLlegada: "17/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Recepcion",
    kilometraje: "4000"
  },
  {
    id: 2,
    placa: "SDSGFS8416",
    nombre: "Guillermo Sifuente",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaLlegada: "16/01/2023 08:00:00",
    servicio: "Mantenimiento Flexible",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Pendiente",
    kilometraje: "5000"
  },
  {
    id: 3,
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "JAC",
    horaLlegada: "19/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Recepcion",
    kilometraje: "600"
  },
  {
    id: 4,
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaLlegada: "19/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Secado",
    kilometraje: "3000"
  },
  {
    id: 5,
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaLlegada: "19/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Asignacion",
    kilometraje: "3000"
  },
];
