export const DataAsignacionMecanico = [
  {
    id: 1,
    ot: "22324267",
    placa: "VGGJ4464",
    nombre: "Rodolfo Gilardi",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaRecepcion: "13:00 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoAsignacion: "Pendiente",
    ubicacion: "Asignacion",
    kilometraje: "4000"
  },
  {
    id: 2,
    ot: "22324267",
    placa: "SDSGFS8416",
    nombre: "Guillermo Sifuente",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaRecepcion: "08:00 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento Flexible",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoAsignacion: "Pendiente",
    ubicacion: "Asignacion",
    kilometraje: "5000"
  },
  {
    id: 3,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "JAC",
    horaRecepcion: "13:00 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoAsignacion: "Listo",
    ubicacion: "Asignacion",
    kilometraje: "600"
  },
  {
    id: 4,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaRecepcion: "13:00 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoAsignacion: "Pendiente",
    ubicacion: "Asignacion",
    kilometraje: "3000"
  },
  {
    id: 5,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaRecepcion: "13:00 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoAsignacion: "Listo",
    ubicacion: "No Asignado",
    kilometraje: "3000"
  },
];


export const DataAsignacionServicio = [
  {
    id: 1,
    ot: "22324267",
    placa: "VGGJ4464",
    nombre: "Rodolfo Gilardi",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "En proceso",
    ubicacion: "Mantenimiento",
    salidaUnidad: "Pendiente",
    kilometraje: "4000"
  },
  {
    id: 2,
    ot: "22324267",
    placa: "VGGJ4464",
    nombre: "Rodolfo Gilardi",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Control de calidad",
    salidaUnidad: "Pendiente",
    kilometraje: "4000"
  },
  {
    id: 3,
    ot: "22324267",
    placa: "SDSGFS8416",
    nombre: "Guillermo Sifuente",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "08:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento Flexible",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Lavado",
    salidaUnidad: "Pendiente",
    kilometraje: "5000"
  },
  {
    id: 4,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Secado",
    salidaUnidad: "Pendiente",
    kilometraje: "600"
  },
  {
    id: 5,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Pre Entrega",
    salidaUnidad: "Pendiente",
    kilometraje: "3000"
  },
  {
    id: 6,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Entrega",
    salidaUnidad: "Pendiente",
    kilometraje: "3000"
  },
  {
    id: 7,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Terminado",
    ubicacion: "Entrega",
    salidaUnidad: "Unidad Entregada",
    kilometraje: "3000"
  },
  {
    id: 8,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Pendiente",
    ubicacion: "Mantenimiento",
    salidaUnidad: "Pendiente",
    kilometraje: "3000"
  },
  {
    id: 9,
    ot: "22324267",
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    apellido: "Fuentes Madueño",
    telefono: "987456321",
    marca: "JAC",
    horaInicioMantenimiento: "10:40 AM",
    horaFinMantenimiento: "2:00 PM",
    horaRecepcion: "13:00 PM",
    horaAsignacion: "15:30 PM",
    horaEstimada: "11:45 AM",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estadoMantenimiento: "Pendiente",
    ubicacion: "Mantenimiento",
    salidaUnidad: "Pendiente",
    kilometraje: "3000"
  },
];
