export const DataDerco = [{
    id: 1,
    placa: "ABC123",
    nombre: "Rodolfo Gilardi",
    apellido: "Juan Perez",
    telefono: "987456321",
    marca: "SUSUKI",
    loca: "SURCO",
    servicio: "Mantenimiento preventivo",
    asesor: "David Martinez",
    estado: "Recepcion",
    kilometraje: "5000",
    horaCita: "13:00",
    cita: "Si",
    estadoCliente: "Pendiente"
},
{
    id: 2,
    placa: "ABC124",
    nombre: "Juan Perez",
    apellido: "Juan Perez",
    telefono: "874563215",
    marca: "JAC",
    loca: "SURQUILLO",
    servicio: "Activacion de Sistemas GPS",
    asesor: "",
    kilometraje: "",
    horaCita: "",
    estado: "Pendiente",
    cita: "Si",
    estadoCliente: "Asistio"
},
{
    id: 3,
    placa: "ABC125",
    nombre: "Lucas Martinez",
    apellido: "Juan Perez",
    telefono: "963258741",
    marca: "MAZDA",
    loca: "CAMACHO",
    servicio: "Mantenimiento Preventivo",
    cita: "No",
    asesor: "Guillermo Sifuentes",
    estado: "Recepcion",
    kilometraje: "8000",
    horaCita: "23:00",
    estadoCliente: "No asistio"
    
},
{
    id: 4,
    placa: "ABC127",
    nombre: "Lucia Lopez",
    apellido: "Juan Perez",
    telefono: "987123654",
    marca: "SUSUKI",
    loca: "SURCO",
    servicio: "Mantenimiento Preventivo",
    cita: "No",
    asesor: "",
    kilometraje: "",
    horaCita: "",
    estado: "Pendiente",
    estadoCliente: "Asistio"
},
{
    id: 5,
    placa: "ABC127",
    nombre: "Juaana Davila",
    apellido: "Juan Perez",
    telefono: "987123654",
    marca: "JAC",
    loca: "CAMACHO",
    servicio: "Mantenimiento Preventivo",
    cita: "Si",
    asesor: "Nick Arenas Levano",
    estado: "Recepcion",
    kilometraje: "10000",
    horaCita: "20:00",
    estadoCliente: "No asistio"
}]