export const DataRecepcion = [
  {
    id: 1,
    placa: "VGGJ4464",
    nombre: "Rodolfo Gilardi",
    telefono: "987456321",
    marca: "SUSUKI",
    horaLlegada: "17/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Atendido",
  },
  {
    id: 2,
    placa: "SDSGFS8416",
    nombre: "Guillermo Sifuente",
    telefono: "987456321",
    marca: "SUSUKI",
    horaLlegada: "16/01/2023 08:00:00",
    servicio: "Mantenimiento Flexible",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Pendiente",
  },
  {
    id: 3,
    placa: "SDF7154",
    nombre: "Pepe Lucho",
    telefono: "987456321",
    marca: "JAC",
    horaLlegada: "19/01/2023 13:00:00",
    servicio: "Mantenimiento preventivo",
    Adicional:"Lavado",
    asesor: "David Martinez",
    estado: "Atendido",
  },
];
